# Generated by Django 4.0.3 on 2022-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useracocunt_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracocunt',
            name='pin',
            field=models.CharField(default='', max_length=8),
        ),
    ]
