# Generated by Django 4.0.3 on 2022-03-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useracocunt_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracocunt',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useracocunt',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useracocunt',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useracocunt',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useracocunt',
            name='user_name',
        ),
    ]
