# Generated by Django 4.0.3 on 2022-03-18 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_remove_useracocunt_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAcocunt',
            new_name='UserAccount',
        ),
    ]
