# Generated by Django 4.0.3 on 2022-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_useracocunt_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
