# Generated by Django 4.0.3 on 2022-03-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_useraccount_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profilePic',
            field=models.FileField(default='anonymous.png', upload_to='accounts/'),
        ),
    ]
