# Generated by Django 3.1.4 on 2022-04-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_useraccount_address_alter_useraccount_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WeatherStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_stat', models.CharField(blank=True, max_length=200, null=True)),
                ('weather_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=150, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('cloud_density', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
