# Generated by Django 4.0.3 on 2022-04-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_weatherstat_wind_speed_alter_useraccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstat',
            name='time_noted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
